#!/usr/bin/env bash
# DDL de licencias manuales (30-jul-2026) — correr ANTES del deploy correspondiente.
# Uso:  bash infra/ddl-2026-07-30-licencias-manuales.sh
set -euo pipefail
cd "$(dirname "$0")/.."

bash infra/run-ddl.sh 'CREATE TABLE IF NOT EXISTS "LicenciasManuales" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "EmpleadoId" integer NOT NULL REFERENCES "Empleados"("Id"),
    "Desde" date NOT NULL,
    "Hasta" date,
    "Motivo" character varying(100) NOT NULL,
    "CreadaPor" character varying(120) NOT NULL,
    "CreadaUtc" timestamp with time zone NOT NULL
);
CREATE INDEX IF NOT EXISTS "IX_LicenciasManuales_EmpleadoId" ON "LicenciasManuales" ("EmpleadoId");
ALTER TABLE "Novedades" ADD COLUMN IF NOT EXISTS "EsManual" boolean NOT NULL DEFAULT FALSE;'
