#!/usr/bin/env bash
# DDL del asistente IA (30-jul-2026) — correr ANTES del deploy correspondiente.
# Tablas de auditoría del asistente + índice por fecha en Novedades (las consultas por
# rango del asistente hacían seq scan).
# Uso:  bash infra/ddl-2026-07-30-asistente.sh
set -euo pipefail
cd "$(dirname "$0")/.."

bash infra/run-ddl.sh 'CREATE TABLE IF NOT EXISTS "AsistenteTurnos" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UsuarioId" integer NOT NULL REFERENCES "Usuarios"("Id"),
    "CreadoUtc" timestamp with time zone NOT NULL,
    "Pregunta" text,
    "Respuesta" text,
    "Modelo" character varying(60) NOT NULL,
    "Vueltas" integer NOT NULL DEFAULT 0,
    "DuracionMs" integer NOT NULL DEFAULT 0,
    "TokensEntrada" integer NOT NULL DEFAULT 0,
    "TokensSalida" integer NOT NULL DEFAULT 0,
    "TokensCacheados" integer NOT NULL DEFAULT 0,
    "CostoUsd" numeric(10,6) NOT NULL DEFAULT 0,
    "Ok" boolean NOT NULL DEFAULT FALSE,
    "Error" character varying(500)
);
CREATE INDEX IF NOT EXISTS "IX_AsistenteTurnos_UsuarioId" ON "AsistenteTurnos" ("UsuarioId");
CREATE INDEX IF NOT EXISTS "IX_AsistenteTurnos_CreadoUtc" ON "AsistenteTurnos" ("CreadoUtc");
CREATE TABLE IF NOT EXISTS "AsistenteHerramientasUso" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "TurnoId" integer NOT NULL REFERENCES "AsistenteTurnos"("Id") ON DELETE CASCADE,
    "Herramienta" character varying(60) NOT NULL,
    "ArgsJson" character varying(2000),
    "DuracionMs" integer NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS "IX_AsistenteHerramientasUso_TurnoId" ON "AsistenteHerramientasUso" ("TurnoId");
CREATE INDEX IF NOT EXISTS "IX_Novedades_Fecha" ON "Novedades" ("Fecha");'
